// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc3
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIService_GetTriangleWithLoop_FullMethodName    = "/api.APIService/GetTriangleWithLoop"
	APIService_GetTriangleWithNonLoop_FullMethodName = "/api.APIService/GetTriangleWithNonLoop"
	APIService_CatchMeIfYouCan_FullMethodName        = "/api.APIService/CatchMeIfYouCan"
	APIService_GetSummary_FullMethodName             = "/api.APIService/GetSummary"
)

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIServiceClient interface {
	GetTriangleWithLoop(ctx context.Context, in *TriangleRequest, opts ...grpc.CallOption) (*TriangleResponse, error)
	GetTriangleWithNonLoop(ctx context.Context, in *TriangleRequest, opts ...grpc.CallOption) (*TriangleResponse, error)
	CatchMeIfYouCan(ctx context.Context, in *CatchMeRequest, opts ...grpc.CallOption) (*CatchMeResponse, error)
	GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type aPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServiceClient(cc grpc.ClientConnInterface) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetTriangleWithLoop(ctx context.Context, in *TriangleRequest, opts ...grpc.CallOption) (*TriangleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriangleResponse)
	err := c.cc.Invoke(ctx, APIService_GetTriangleWithLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetTriangleWithNonLoop(ctx context.Context, in *TriangleRequest, opts ...grpc.CallOption) (*TriangleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriangleResponse)
	err := c.cc.Invoke(ctx, APIService_GetTriangleWithNonLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) CatchMeIfYouCan(ctx context.Context, in *CatchMeRequest, opts ...grpc.CallOption) (*CatchMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatchMeResponse)
	err := c.cc.Invoke(ctx, APIService_CatchMeIfYouCan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, APIService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
// All implementations must embed UnimplementedAPIServiceServer
// for forward compatibility.
type APIServiceServer interface {
	GetTriangleWithLoop(context.Context, *TriangleRequest) (*TriangleResponse, error)
	GetTriangleWithNonLoop(context.Context, *TriangleRequest) (*TriangleResponse, error)
	CatchMeIfYouCan(context.Context, *CatchMeRequest) (*CatchMeResponse, error)
	GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	mustEmbedUnimplementedAPIServiceServer()
}

// UnimplementedAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServiceServer struct{}

func (UnimplementedAPIServiceServer) GetTriangleWithLoop(context.Context, *TriangleRequest) (*TriangleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTriangleWithLoop not implemented")
}
func (UnimplementedAPIServiceServer) GetTriangleWithNonLoop(context.Context, *TriangleRequest) (*TriangleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTriangleWithNonLoop not implemented")
}
func (UnimplementedAPIServiceServer) CatchMeIfYouCan(context.Context, *CatchMeRequest) (*CatchMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CatchMeIfYouCan not implemented")
}
func (UnimplementedAPIServiceServer) GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedAPIServiceServer) mustEmbedUnimplementedAPIServiceServer() {}
func (UnimplementedAPIServiceServer) testEmbeddedByValue()                    {}

// UnsafeAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServiceServer will
// result in compilation errors.
type UnsafeAPIServiceServer interface {
	mustEmbedUnimplementedAPIServiceServer()
}

func RegisterAPIServiceServer(s grpc.ServiceRegistrar, srv APIServiceServer) {
	// If the following call pancis, it indicates UnimplementedAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIService_ServiceDesc, srv)
}

func _APIService_GetTriangleWithLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriangleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetTriangleWithLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_GetTriangleWithLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetTriangleWithLoop(ctx, req.(*TriangleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetTriangleWithNonLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriangleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetTriangleWithNonLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_GetTriangleWithNonLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetTriangleWithNonLoop(ctx, req.(*TriangleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_CatchMeIfYouCan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatchMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CatchMeIfYouCan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_CatchMeIfYouCan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CatchMeIfYouCan(ctx, req.(*CatchMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetSummary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIService_ServiceDesc is the grpc.ServiceDesc for APIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTriangleWithLoop",
			Handler:    _APIService_GetTriangleWithLoop_Handler,
		},
		{
			MethodName: "GetTriangleWithNonLoop",
			Handler:    _APIService_GetTriangleWithNonLoop_Handler,
		},
		{
			MethodName: "CatchMeIfYouCan",
			Handler:    _APIService_CatchMeIfYouCan_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _APIService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
